M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Wed 15 Nov 2023 11:42:17 AM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-15T11:42:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.476
%
G90
G05
T1
X181.424Y-83.144
X189.924Y-83.144
T0
M30
